### ISSUE TITLE
data.json not being created on installation

### ISSUE THREAD

**Issue by Nevimmu** [Zepoze/manladag-real-cli#2]
**Issue :** when installing the program with the command given `sudo npm install --global @manladag/cli` the file `data.json` isn't created.

**Expected result :** the file `data.json` is created when the program is installed.

When added manually afterward, the program run perfectly fine.

**Comment by Zepoze** [comment]
Please install this version on the branch "installation-improvement" and release the logs errors if there are any

**Comment by Zepoze** [comment]
### NEED SOME EXPLANATION
The file ***data.json*** did not want to created because a (stupid) error occurred in this package see this [issue](https://github.com/Zepoze/manladag-lelscanv/issues/3)
